# Generated by VisualGDB

LOCAL_PATH := $(call my-dir)


include $(LOCAL_PATH)/Fb2.mk

include $(CLEAR_VARS)
LOCAL_MODULE    := fb2
LOCAL_SRC_FILES := fb2.cpp
LOCAL_C_INCLUDES := 
LOCAL_LDLIBS := -lz -llog
LOCAL_CFLAGS := 
LOCAL_CPPFLAGS := 
LOCAL_LDFLAGS := -Wl,--gc-sections 
LOCAL_STATIC_LIBRARIES := fb2toepub unzip101e


LOCAL_SHARED_LIBRARIES := 
include $(BUILD_SHARED_LIBRARY)