package com.foobnix.dao2;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BOOKMARK".
 */
@Entity
public class Bookmark {

    @Id(autoincrement = true)
    private Long id;
    private String path;
    private String text;
    private Integer page;
    private Long time;
    private Integer type;
    private String color;

    @Generated
    public Bookmark() {
    }

    public Bookmark(Long id) {
        this.id = id;
    }

    @Generated
    public Bookmark(Long id, String path, String text, Integer page, Long time, Integer type, String color) {
        this.id = id;
        this.path = path;
        this.text = text;
        this.page = page;
        this.time = time;
        this.type = type;
        this.color = color;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Integer getPage() {
        return page;
    }

    public void setPage(Integer page) {
        this.page = page;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

}
