package com.foobnix.dao2;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.foobnix.dao2.FileMeta;

import com.foobnix.dao2.FileMetaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileMetaDaoConfig;

    private final FileMetaDao fileMetaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileMetaDaoConfig = daoConfigMap.get(FileMetaDao.class).clone();
        fileMetaDaoConfig.initIdentityScope(type);

        fileMetaDao = new FileMetaDao(fileMetaDaoConfig, this);

        registerDao(FileMeta.class, fileMetaDao);
    }
    
    public void clear() {
        fileMetaDaoConfig.clearIdentityScope();
    }

    public FileMetaDao getFileMetaDao() {
        return fileMetaDao;
    }

}
