package com.foobnix.dao2;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "RECENT_META".
 */
@Entity
public class RecentMeta {

    @Id
    private String path;
    private Integer progress;
    private Long time;

    @Generated
    public RecentMeta() {
    }

    public RecentMeta(String path) {
        this.path = path;
    }

    @Generated
    public RecentMeta(String path, Integer progress, Long time) {
        this.path = path;
        this.progress = progress;
        this.time = time;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Integer getProgress() {
        return progress;
    }

    public void setProgress(Integer progress) {
        this.progress = progress;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
