package com.foobnix.dao2;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "STAR_META".
 */
@Entity
public class StarMeta {

    @Id
    private String path;
    private Long time;

    @Generated
    public StarMeta() {
    }

    public StarMeta(String path) {
        this.path = path;
    }

    @Generated
    public StarMeta(String path, Long time) {
        this.path = path;
        this.time = time;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getTime() {
        return time;
    }

    public void setTime(Long time) {
        this.time = time;
    }

}
