.\" Copyright (c) 2001-2003 Leon Bottou, Yann Le Cun, Patrick Haffner,
.\" Copyright (c) 2001 AT&T Corp., and Lizardtech, Inc.
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual. Otherwise check the web site
.\" of the Free Software Foundation at http://www.fsf.org.
.TH DJVM 1 "10/11/2001" "DjVuLibre-3.5" "DjVuLibre-3.5"
.de SS
.SH \\0\\0\\0\\$*
..
.SH NAME
djvm \- Manipulate bundled multi-page DjVu documents.

.SH SYNOPSIS
.SS Creating a bundled document:
.BI "djvm -c[reate] " "doc.djvu" " " "page1.djvu" " ... " "pageN.djvu"
.SS Inserting:
.BI "djvm -i[nsert] " "doc.djvu" " " "page.djvu" " [" "pagenum" "]"
.SS Removing:
.BI "djvm -d[elete] " "doc.djvu" " " "pagenum"
.SS Listing:
.BI "djvm -l[ist] " "doc.djvu"

.SH DESCRIPTION
This program creates or modifies a bundled multi-page DjVu document.
Multi-page bundled documents can be used directly or converted
to indirect document using command
.BR djvmcvt .

.SH OPTIONS
.TP
.B -c[reate]
Create a bundled DjVu document named
.I doc.djvu
by collecting files
.I page1.djvu
to 
.IR pageN.djvu .
.TP
.B -i[nsert]
Modify the bundled DjVu document named
.I doc.djvu
by inserting file
.I page.djvu
as page
.IR pagenum .
Omitting argument
.I pagenum
means that the page should be appended at the end of the document.
File 
.I page.djvu
also can be a multi-page DjVu document.
All pages will be inserted at the specified location.
.TP
.B -d[elete]
Remove page
.I pagenum
from the bundled multi-page DjVu document
.IR doc.djvu .
.TP
.B -l[ist]
List all component files in the multi-page DjVu document
.IR doc.djvu .

.SH CREDITS
This program was initially written by Andrei Erofeev
<andrew_erofeev@yahoo.com> and was improved by Bill Riemers
<docbill@sourceforge.net> and many others.

.SH SEE ALSO
.BR djvu (1),
.BR djvmcvt (1)

